### ISSUE TITLE
Meshes kept in assets after despawning

### ISSUE THREAD

**Issue by MiniaczQ** [BenCantCode/Petra#1]
Hello, I'm working on a similar system (also first project in Rust)
and I've noticed you don't try to delete terrain mesh from the assets when unloading chunks.
It may be a memory leak (unless I don't know about some bevy mechanic), but it's likely you simply didn't bother with it yet.

**Comment by MiniaczQ** [comment]
Can't believe I've overlooked that meshes are owned by the entity so they probably get deleted with the entity.
Sorry for the mess and gl with the project :)

**Comment by BenCantCode** [comment]
No problem, thank you so much for your interest!
